### ISSUE TITLE
Change colors dynamically afterwards

### ISSUE THREAD

**Issue by finnmargraf** [BlankParticle/tailwind-plugin-realtime-colors#2]
I really appreciate this plugin and use it with great pleasure.
However, there is one special feature I want to implement into my app.
I want to set the primary colour based on a colour picker that the user has in his settings menu.
Is there (or will there be) a usable solution that is compatible with the plugin?

`tailwind.config.js`
```js
import realtimeColors from 'tailwind-plugin-realtime-colors';

/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{html,js,svelte,ts}'],
	theme: {
		extend: {
			fontFamily: {
				sans: ['Inter', 'sans-serif']
			}
		}
	},
	darkMode: 'class',
	plugins: [
		realtimeColors({
			colors: {
				text: '#f2ece8',
				background: '#040404',
				primary: '#2456df',
				secondary: '#000',
				accent: '#000'
			}
		})
	]
};
```

**Comment by BlankParticle** [comment]
I think I can do something for that, maybe use a CSS variable that you define yourself and gets picked up by the config

I will look into it

**Comment by finnmargraf** [comment]
Wow, thanks for the incredibly quick reply.
I really appreciate it 👍🏻

**Comment by BlankParticle** [comment]
Hey @SachsenspieltCoding, I added a feature in #3 for your usecase, check out if it solves your problem.
Also suggest if you have any ideas.

**Comment by finnmargraf** [comment]
Huge props for the incredibly fast implementation.
I will try it when I am back home (in ~2h)

**Comment by BlankParticle** [comment]
🎉 v1.2.0 is now out on npm fixing this issue
